REM INSERTING into ACTUALIZATION_LOG
SET DEFINE OFF;
Insert into ACTUALIZATION_LOG (INSERT_DATE,APP_VERSION,DB_VERSION,SCRIPT,STATUS) values (to_date('23/01/25','RR/MM/DD'),null,'1.00.00','validator4apex_010000_install.sql','1');
